"""initial tables

Revision ID: 59515655fb30
Revises: 
Create Date: 2026-08-24 09:26:50.852774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.base import UTCDateTime


revision: str = '59515655fb30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('buying_power', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_created_at'), ['created_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=True)

    op.create_table('risk_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('original_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_status'), ['status'], unique=False)

    op.create_table('trade_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_proposals_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_symbol'), ['symbol'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('filled_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_agent_id'))

    op.drop_table('orders')
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_proposals_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_agent_id'))

    op.drop_table('trade_proposals')
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_created_at'))

    op.drop_table('risk_decisions')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_created_at'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    # ### end Alembic commands ###
