import { askClaudeJson } from "./llm";
import type { MarketSnapshot, NewsItem } from "@/lib/contracts/research";
export interface AgentMessage { role: string; stance: "bullish" | "bearish" | "neutral"; headline: string; body: string; confidence: number | null; }
export interface CIOSynthesis { symbol: string; direction: string; confidence: number; summary: string; catalysts: string[]; risks: string[]; recommendation: string; }
const J = "Respond with valid JSON only. No markdown or code fences.";
export async function runNewsAgent(s, news) { const r = await askClaudeJson(`You are Sage, the News Intelligence agent. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<0-100>}`, news.length ? news.map(n => n.headline).join("\n") : `No news for ${s}. Use training knowledge.`); return { role: "news", ...r }; }
export async function runMarketResearchAgent(s, snap) { const r = await askClaudeJson(`You are Vector, the Market Structure agent. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<<0-100>}`, `${s} @ $${snap.price} RSI:${snap.rsi14} Regime:${snap.regime} Vol:${snap.realizedVol30dAnnPct}%`); return { role: "market_research", ...r }; }
export async function runBullAgent(s, snap, nM, mM) { const r = await askClaudeJson(`You are Atlas, the Bull Case agent. ${J} Return: {"stance":"bullish","headline":"<one sentence>","body":"<2+ sentences>","confidence":<<0-100>}`, `${s} @ $${snap.price} Sage: ${nM.headline} Vector: ${mM.headline}`); return { role: "bull", ...r, stance: "bullish" }; }
export async function runBearAgent(s, snap, nM, mM) { const r = await askClaudeJson(`You are Mara, the Risk Challenge agent. ${J} Return: {"stance":"bearish","headline":"<one sentence>","body":"<2+ sentences>","confidence":<<0-100>}`, `${s} @ $${snap.price} Sage: ${nM.headline} Vector: ${mM.headline}`); return { role: "bear", ...r, stance: "bearish" }; }
export async function runCIOAgent(s, snap, nM, mM, bM, beM) { const raw = await askClaudeJson(`You are North, the CIO. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<0-100>,"direction":"BUY"|"SELL"
|"HOLD","catalysts":[],"risks":[],"recommendation":"<actionable>"}`, `${s} Sage: ${nM.headline} Vector: ${mM.headline} Atlas: ${bM.headline} Mara: ${beM.headline}`); return { message: { role: "investment_committee", stance: raw.stance, headline: raw.headline, body: raw.body, confidence: raw.confidence }, thesis: { symbol: s, direction: raw.direction, confidence: raw.confidence, summary: raw.headline, catalysts: raw.catalysts ?? [], risks: raw.risks ?? [], recommendation: raw.recommendation } }; }
export async function runCrisisNewsAgent(s, news) { const r = await askClaudeJson(`You are Sentinel, Crisis News agent. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<0-100>}`, news.length ? news.map(n => n.headline).join("\n") : `No news for ${s}.`); return { role: "crisis_news", ...r }; }
export async function runCrisisMarketAgent(s, snap) { const r = await askClaudeJson(`You are Radar, Crisis Market agent. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<<0-100>}`, `${s} @ $${snap.price} Vol: ${snap.realizedVol30dAnnPct}% RSI: ${snap.rsi14}`); return { role: "crisis_market", ...r }; }
export async function runCrisisRiskAgent(s, snap, mM) { const r = await askClaudeJson(`You are Gauge, Crisis Risk Analyst. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<<0-100>}`, `${s} Radar: ${mM.headline}`); return { role: "crisis_risk_analyst", ...r }; }
export async function runCrisisOptionsAgent(s, snap) { const r = await askClaudeJson(`You are Hedge, Crisis Options agent. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<0-100>}`, `${s} Vol: ${snap.realizedVol30dAnnPct}%`); return { role: "crisis_options", ...r }; }
export async function runCrisisCommitteeAgent(s, snap, nM, mM, rM, oM) { const raw = await askClaudeJson(`You are Apex, Crisis Committee chair. ${J} Return: {"stance":"bullish"|"bearish"|"neutral","headline":"<one sentence>","body":"<2+ sentences>","confidence":<0-100>,"direction":"BUY"|"SELL"
|"HOLD","catalysts":[],"risks":[],"recommendation":"<actionable>"}`, `${s} Sentinel: ${nM.headline} Radar: ${mM.headline} Gauge: ${rM.headline} Hedge: ${oM.headline}`); return { message: { role: "crisis_committee", stance: raw.stance, headline: raw.headline, body: raw.body, confidence: raw.confidence }, thesis: { symbol: s, direction: raw.direction, confidence: raw.confidence, summary: raw.headline, catalysts: raw.catalysts ?? [], risks: raw.risks ?? [], recommendation: raw.recommendation } }; }
